### ISSUE TITLE
[Platform Guide] Writing a Getting Started page

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/website#101]
We have a "Getting Started" section that explains how to install Prometheus-Operator.

We still need other pages to teach how to deploy Prometheus, Alertmanager, Thanos Ruler and Prometheus Agent. We don't plan to cover all deployables in the same page, but we can start with the basics: Prometheus + Alertmanager.

---

Planned content for the page:
* Explain RBAC permissions needed, add example YAML
* Re-use "Deploying Prometheus" and "Deploying Alertmanager" from Developer guides, while removing them from the original place.
* We will also mention AlertmanagerConfig and PrometheusRules but from a "Platform Engineer" perspective. Platform Engineers provide decent defaults while letting developer merge their own configuration with extra AlertmanagerConfig and rules.

**Comment by ArthurSens** [comment]
this is fixed, right @AshwinSriram11 ?

**Comment by ArthurSens** [comment]
Oh nevermind, the PR we merged was about developer guide 😬

**Comment by AshwinSriram11** [comment]
Actually the opposite. The open PR is on the Developer Guide.

**Comment by ArthurSens** [comment]
Oh ok, so let's close this one
