### ISSUE TITLE
Missing escaping for HTML special characters on API page

### ISSUE THREAD

**Issue by juliusv** [prometheus-operator/website#13]
See:

![missing-escaping](https://user-images.githubusercontent.com/538008/114383795-3d3cfb00-9b8e-11eb-9af8-3fc098b06843.png)

It should read `alertmanager-<alertmanager-name>`, not `alertmanager-`, but the `<` / `>` are interpreted as HTML entities, as they are not escaped on the API page (https://prometheus-operator.dev/docs/operator/api/).

**Comment by simonpasquier** [comment]
It should be fixed by https://github.com/prometheus-operator/prometheus-operator/pull/5056
