### ISSUE TITLE
API page has rendering issues

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/website#4]
Seems like the middle part of the site is not restricted in width and overlaps with the right navigation panel.

It looks like in the screenshot below.
![Screenshot_20210318_204854](https://user-images.githubusercontent.com/3531758/111688897-a64d7f00-882b-11eb-9c5a-6f6febb1fd6a.png)

**Comment by metalmatze** [comment]
Yup, seen that...
It certainly would be better if we could make the container fluid.
