### ISSUE TITLE
troubleshooting page: Image broken

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/website#9]
https://prometheus-operator.dev/docs/operator/troubleshooting/ The diagram image is broken for me.

**Comment by paulfantom** [comment]
This is possibly because [`synchronize.sh` is copying image into `images/...`](https://github.com/prometheus-operator/website/blob/main/synchronize.sh#L22) which is not picked up by hugo.

**Comment by metalmatze** [comment]
Weird it isn't? Worked locally a few weeks ago.
If we know what path to copy it to we can simply update the synchronize.sh :)
